options:
    formatter: stylish


files:
    include: 'css/**/*.scss'


rules:
    border-zero:
        - 1
        -   convention: none

    brace-style:
        - 1
        -   style: 1tbs
            allow-single-line: false

    clean-import-paths:
        - 1
        -   leading-underscore: false
            filename-extension: false

    empty-args:
        - 1
        -   include: false

    empty-line-between-blocks:
        - 1
        -   include: true
            allow-single-line-rulesets: false

    extends-before-declarations:
        - 1

    extends-before-mixins:
        - 1

    final-newline:
        - 1
        -   include: true

    force-attribute-nesting:
        - 0

    force-element-nesting:
        - 0

    foce-pseudo-nesting:
        - 0

    function-name-format:
        - 1
        -   allow-leading-underscore: true
            convention: hyphenatedlowercase

    hex-length:
        - 1
        -   style: short

    hex-notation:
        - 1
        -   style: uppercase

    indentation:
        - 1
        -   size: 1

    leading-zero:
        - 1
        -   include: false

    mixin-name-format:
        - 1
        -   allow-leading-underscore: true
            convention: hyphenatedlowercase

    mixins-before-declarations:
        - 1

    nesting-depth:
        - 2
        -   max-depth: 4

    no-color-keywords:
        - 0

    no-color-literals:
        - 2
        -   allow-rgba: true

    no-css-comments:
        - 0

    no-debug:
        - 0

    no-duplicate-properties:
        - 2

    no-empty-rulesets:
        - 1

    no-extends:
        - 0

    no-ids:
        - 0

    no-important:
        - 2

    no-invalid-hex:
        - 2

    no-mergable-selectors:
        - 0

    no-misspelled-properties:
        - 2

    no-qualifying-elements:
        - 0

    no-trailing-zero:
        - 1

    no-transition-all:
        - 1

    no-url-protocols:
        - 1

    no-vendor-prefixes:
        - 2

    no-warn:
        - 0

    one-declaration-per-line:
        - 1

    placeholder-in-extends:
        - 0

    placeholder-name-format:
        - 1
        -   allow-leading-underscore: true
            convention: hyphenatedlowercase

    property-sort-order:
        - 1
        -   order: concentric

    quotes:
        - 1
        -   style: single

    shorthand-values:
        - 0

    single-line-per-selector:
        - 1

    space-after-bang:
        - 1
        -   include: false

    space-after-colon:
        - 1
        -   include: true

    space-after-comma:
        - 1
        -   include: true

    space-before-bang:
        - 1
        -   include: true

    space-before-brace:
        - 1
        -   include: true

    space-before-colon:
        - 1
        -   include: false

    space-between-parens:
        - 1
        -   include: false

    trailing-semicolon:
        - 1
        -   include: true

    url-quotes:
        - 1

    variable-for-property:
        - 0

    variable-name-format:
        - 1
        -   allow-leading-underscore: true
            convention: hyphenatedlowercase

    zero-unit:
        - 1
        - include: false
