language: node_js
node_js: stable

install:
    - npm install
    - $(npm bin)/bower install

before_script:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
    - "export DISPLAY=:99.0"

script:
    - npm run lint -s
    - npm test
    - npm run browsertest -s
